be-review 요청
codesquad-member-2020/sidedish-08 pull request #76
Opened 2020-04-28 07:59 UTC by Hyune-c

## 구현된 기능
- 제안서의 요구 기능 모두 완료
  - 분업화를 위한 skeleton 코드
  - DB schema, DAO, DTO 
  - github OAuth 
  - dev/prod 설정 분리 

> 어느 시점에 문제가 생긴 건지 추적하지 못했지만 FE/iOS 의 소스가 합쳐졌습니다
> 지금 올리는 PR 은 해당 파일들을 모두 지우고 올립니다

2020-04-30 05:13 UTC, wheejuni requested changes
수고 많으셨습니다. 
지난 피드백때 말씀드린 내용이 그대로 남아있는 코드들이 군데군데 있는데요, 이 부분에 대해서는 더이상 피드백 드리지 않겠습니다. 제가 생각하는 방향과는 구현이 많이 다르지만, 그렇게 진행하셔야 하는 합리적인 이유를 갖고 계실거라 생각해요. 

아울러 질문하신 내용에 답변 남겨 드립니다. 
리디렉션의 제어권이란 것은 없고, 결국 server-side에서 요청이 인입된 이후 처리를 어떤 handler method에서 담당하게 할지 결정하는 로직은 넣을 수 있습니다. 

HTTP Redirect 헤더를 넣는 것은 서버가 결정한 리디렉션 위치를 클라이언트가 그대로 따르게 전달해주는 것에 불과합니다. 
그런데 지금 프로젝트의 진행 방향을 보면 SPA/Mobile App 기반이라 REST API를 전달해주는 것이 서버사이드의 주 책임이라고 생각하는데, 이 상황에선 API response body에 다음에 호출할 API endpoint등을 전달해주는 것도 좋은 방법이라 생각됩니다. 

어차피 RESTful API에서 그 이상의 책임을 할 수도 없습니다. 

도움 되셨기를 바라고 추가 질문사항 있으시면 이 PR에 댓글로 전달해주세요. 감사합니다!

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/config/AuthProperties.java
> +
변수에 애노테이션이 붙어있는 경우, 한 줄의 공백을 만들어주세요.

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/config/SwaggerConfig.java
> +        .host("localhost:80")
정말 80포트 맞나요?

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/exception/CustomAdvice.java
> +  @ExceptionHandler(Exception.class)
`Exception` 너무 광범위하게 잡으신 것 같네요. 
모든 종류의 checked exception을 잡으신 것 같은데, 정말 이렇게 매핑되어도 괜찮나요.

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/message/AuthMessages.java
> +public class AuthMessages {
이 클래스에서 관리하고 있는 값들은 언제든지 변경될 수 있는 값들이므로 프로퍼티 파일로 관리해 주시고,
심지어 밑의 URL들은 message 인 것도 아니죠. 
프로퍼티 파일로 분리하는 것을 추천합니다.

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/message/DeliveryPrice.java
> +  }
enum 에도 lombok 적용해보세요. 

```java
@AllArgsConstructor
@Getter
public enum DeliveryPrice {
...
```

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/message/CategoryId.java
> +  private long id;
enum의 최대 값 개수가 `int` 의 범위를 벗어나지 않습니다.
https://stackoverflow.com/questions/4468388/maximum-number-of-enum-elements-in-java

꼭 `long` 이 필요할지 다시 고민해주시기 바랍니다.

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/model/dto/Detail.java
> +import static com.codesquad.sidedish08.util.DishUtils.getImageUrlStream;
해당 메소드의 역할범위가 클래스명으로서 기술되어 있는데요,
스태틱 임포트를 하게 되면 `calcPoint` 만 덩그러니 코드상에 남게되어, 어디의 무슨 포인트를 계산? 한다는 건지, 심지어 계산하는 것은 맞나? 어딘가에서 포인트를 갖고 오게 되나? 라고 생각하게 될 겁니다. 
결국 가독성을 해치는 결과를 가져오겠죠. 

리팩토링 포인트를 찾을땐 항상 코드를 작성하는 입장이 아닌 **코드를 읽는 입장, 코드를 인수인계받는 입장** 에서 고민해 주시기를 부탁드립니다. 
도메인에 무관하게 공통된 로직을 담고 있는 클래스가 아닌 이상 스태틱 임포트는 굉장히 제한적으로 해 주시기를 권합니다.

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/model/dto/Main.java
> +public class Main {
클래스명 다시 고민해주세요.

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/model/response/ApiResponse.java
> +  private Map<String, ?> contents;
지난번에도 피드백 드린 것 같은데 여기서도 `?` 쓰셨네요...정확히 알고 사용하시는 것 정말 맞나요. ㅠㅠ
제가 보기엔 이 클래스도 
```java
public class ApiResponse<T> {
    private Map<String, T> contents;
...
```
와 같이 하는게 자연스러워 보이는데요 ㅠ 뭐가 문제죠 ㅠ

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/repository/JdbcCategoryRepository.java
> +  public List<Main> findById(Long id) {
클래스명은 `Category` 가 들어가고, 여기서는 `List<Main>` 을 리턴하네요...

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/repository/JdbcCategoryRepository.java
> +      throw new NoSuchElementException(ErrorMessages.NO_SUCH_ELEMENT_EXCEPTION);
`try-catch` 문 만들지 말고 `null` 체크 로직으로 대체해주세요. 
`if (main == null)` 이런 식으로요.

2020-04-30 05:13 UTC, wheejuni commented on BE/src/main/java/com/codesquad/sidedish08/repository/JdbcCategoryRepository.java
> +        new Object[]{id}, deliveryMapper);
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html#queryForObject-java.lang.String-org.springframework.jdbc.core.RowMapper-java.lang.Object...-

이걸 쓰는게 훨씬 좋아보이네요.

2020-04-30 15:56 UTC, Hyune-c commented on BE/src/main/java/com/codesquad/sidedish08/config/SwaggerConfig.java
> +        .host("localhost:80")
이렇게 했더니 안되더라구요..
나중 버전에는 localhost 로만 바꾸었고, 최종적으로는 실 서버의 ip 를 넣었습니다

2020-04-30 15:57 UTC, Hyune-c commented on BE/src/main/java/com/codesquad/sidedish08/message/DeliveryPrice.java
> +  }
연습을 위해 일부러 Lombok 은 배제해보았습니다

2020-04-30 15:58 UTC, Hyune-c commented on BE/src/main/java/com/codesquad/sidedish08/model/response/ApiResponse.java
> +  private Map<String, ?> contents;
맞습니다. 인지하고 있었는데 누락한거 같아요 ㅠㅠ

2020-05-20 06:46 UTC, honux77 commented on BE/src/main/java/com/codesquad/sidedish08/model/response/ApiResponse.java
> +  private Map<String, ?> contents;
아 맞네요. 나중에 책을 보면서 generic 공부해 주세요. 면접 질문에도 가끔 등장한다고 해요.

2020-05-20 06:48 UTC, merged